#!/bin/bash

isurl=false
nosave=false
noconf=false
update=false

if [ $# -eq 0 ]; then
  echo "Usage: exesh [arglist: -nsu] FILE || \"URL\""
  echo "Options:"
  echo "  -n: dont keep the downloaded file after execution"
  echo "  -y: execute from web without confirmation prompt"
  echo "  -u: update exesh"
  exit 1
fi

if [ $# -ge 2 ]; then
  if [[ "$1" == *"n"* ]]; then
    nosave=true
  fi
  if [[ "$1" == *"y"* ]]; then
    noconf=true
  fi
  if [[ "$1" == *"u"* ]]; then
    update=true
  fi
fi

if [[ "$update" = true ]]; then
  echo "Updating exesh..."
  echo "Fetching from github..."
  sudo curl -SL https://raw.githubusercontent.com/Raais/exesh/main/exesh -o /usr/local/bin/exesh
  sudo chmod a+x /usr/local/bin/exesh
  echo "Done."
  exit 0
fi

if [ $# -eq 1 ]; then
  FILE=$1
fi
if [ $# -ge 2 ]; then
  FILE=$2
fi

URL=${FILE}

if [[ $FILE == http* ]]; then
  if ! curl --output /dev/null --silent --head --fail "$FILE"; then
    echo "Error: $FILE is an invalid URL"
    exit 1
  fi
  FILE=${FILE##*/}
  FILE=${FILE%%\?*}
  FILE=${FILE//\\/}
  isurl=true
  curl -sSL $URL -o $FILE
fi

if [[ ! -f $FILE ]] && [[ "$isurl" = true ]]; then
  echo "File not found: $FILE"
fi

if ! file $FILE | grep -Fiq 'shell'; then
    echo "Error: $FILE is not a valid shell script"
    rm $FILE
    exit 1
fi

if [ ! -x $FILE ]; then
  chmod +x $FILE
fi

RED='\033[0;31m'
NC='\033[0m'

if [[ "$noconf" = false ]] && [[ "$isurl" = true ]]; then
  echo -e "${RED}Executing files from the web can be dangerous, are you sure you want to do this?${NC}"
  read -p "'Y/y' to continue: " -r
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborting..."
    rm $FILE
    exit 1
  fi
fi

if [ $# -gt 2 ]; then
  EXARGS=${@:3}
fi

bash $FILE $EXARGS

if [ $# -eq 2 ] && [[ "$isurl" = true ]]; then
  if [[ "$nosave" = true ]]; then
    rm $FILE
  fi
fi
