#!/bin/bash

# Installation
# sudo curl -sSL https://git.io/J9GSX -o /usr/local/bin/exesh && sudo chmod a+x /usr/local/bin/exesh

isaurl=false
nosave=false
noconf=false
github=false
noexec=false
instll=false

if [ $# -eq 0 ]; then
  echo "Usage: exesh [flaglist: -nygUI] FILE || \"URL\" [your args ...]"
  echo "Options:"
  echo "  -n: dont keep the downloaded file after execution"
  echo "  -y: execute from web without confirmation prompt"
  echo "  -g: github/gist convert to raw"
  echo "  -U: dont execute"
  echo "  -I: install to /usr/local/bin"
  exit 1
fi

if [ "$1" == "--update" ]; then
  echo "Updating exesh..."
  curl -sSL https://raw.githubusercontent.com/Raais/exesh/main/LICENSE | cat
  read -p "Do you accept the terms of the license? (y/n): " -r
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborting..."
    exit 1
  fi
  echo "Fetching from github..."
  sudo curl -SL https://raw.githubusercontent.com/Raais/exesh/main/exesh -o /usr/local/bin/exesh
  sudo chmod a+x /usr/local/bin/exesh
  echo "Done."
  exit 0
fi

if [ $# -ge 2 ]; then
  if [[ "$1" == *"n"* ]]; then
    nosave=true
  fi
  if [[ "$1" == *"y"* ]]; then
    noconf=true
  fi
  if [[ "$1" == *"g"* ]]; then
    github=true
  fi
  if [[ "$1" == *"U"* ]]; then
    noexec=true
  fi
  if [[ "$1" == *"I"* ]]; then
    instll=true
  fi
fi

if [ $# -eq 1 ]; then
  FILE=$1
fi
if [ $# -ge 2 ]; then
  FILE=$2
fi

URL=${FILE}

if [[ "$github" = true ]]; then
  if ! echo "$URL" | grep -Fiq "githubusercontent"; then
    if echo "$URL" | grep -Fiq "gist"; then
        URL="${URL}/raw/"
        URL=${URL/github/"githubusercontent"}
    else
        URL=${URL/blob\//}
        URL=${URL/github/"raw.githubusercontent"}
    fi
  fi
fi

if [[ $FILE == http* ]]; then
  if ! curl --output /dev/null --silent --head --fail "$URL"; then
    echo "Error: $URL is an invalid URL"
    exit 1
  fi
  FILE=${FILE##*/}
  FILE=${FILE%%\?*}
  FILE=${FILE//\\/}
  isaurl=true
  curl -sSL "$URL" -o "$FILE"
fi

if [[ ! -f $FILE ]] && [[ "$isaurl" = true ]]; then
  echo "File not found: $FILE"
fi

if ! file "$FILE" | grep -Fiq 'shell'; then
    echo "Error: $FILE is not a valid shell script"
    if [[ "$isaurl" = true ]]; then
      rm "$FILE"
    fi
    exit 1
fi

if [ ! -x "$FILE" ]; then
  chmod +x "$FILE"
fi

RED='\033[0;31m'
NC='\033[0m'

if [[ "$noconf" = false ]] && [[ "$isaurl" = true ]]; then
  echo -e "${RED}Executing files from the web can be dangerous${NC}"
  read -p "Are you sure you want to do this? [y/n] " -r
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborting..."
    rm "$FILE"
    exit 1
  fi
fi

if [ $# -gt 2 ]; then
  EXARGS="${@: 3}"
fi

if [[ "$noexec" = false ]]; then
  bash "$FILE" $EXARGS
fi

if [[ "$instll" = true ]]; then
  echo "Installing to /usr/local/bin..."
  sudo mv "$FILE" /usr/local/bin/
  echo "Done."
fi

if [[ "$isaurl" = true ]] && [[ "$instll" = false ]]; then
  if [[ "$nosave" = true ]]; then
    rm "$FILE"
  fi
fi
